### ISSUE TITLE
request's encoding is corrupt

### ISSUE THREAD

**Issue by mr-cloud** [mr-cloud/test#114]
When trying to setup gzip request, I get from server a 400 response:
```
The request content was malformed:
The request's encoding is corrupt
	at requests.Requester$$anon$1.readBytesThrough(Requester.scala:356)
	at geny.Readable.writeBytesTo(Writable.scala:93)
	at geny.Readable.writeBytesTo$(Writable.scala:93)
	at requests.Requester$$anon$1.writeBytesTo(Requester.scala:165)
	at requests.Requester.apply(Requester.scala:114)
```

Please see attached simple main that shows the issue.

Note: apache client works find against  server, hence I think it's an issue in requests impl
[HttpServerRoutingMinimal.zip](https://github.com/com-lihaoyi/requests-scala/files/6733635/HttpServerRoutingMinimal.zip)

ID: 88
Original Author: yairogen
link: <a href="https://github.com/com-lihaoyi/requests-scala/issues/88">Original Link</a>

**Comment by mr-cloud** [comment]
@lihaoyi  is this a known issue?

Original Author:yairogen

**Comment by mr-cloud** [comment]
@yairogen any chance you could provide a build file to go along with the source code? Otherwise I'm not sure how to reproduce 
Original Author:lihaoyi

**Comment by yairogen** [comment]
@mr-cloud I'm afaraid it's been too long and I don't have source code to give you. I can say that we worked around this by Compressing the string data ourselves with GZIPOutputStream and setting HttpHeaders.CONTENT_ENCODING to "gzip" manually:
something like this:
```
requests
            .delete(
              url = my_url,
              data = data.get.gzipped(), // this is where we zipped the data ourselves
              sslContext = my_context,
              readTimeout = readTimeout,
              headers = (headers ++ Iterable((HttpHeaders.CONTENT_ENCODING, "gzip"))),
              check = check,
              verifySslCerts = false
            )
```
